swagger: "2.0"
info:
  title: "My API"
  version: "1.0.0"
  description: "My API description"
  contact:
    name: "My API Team"
basePath: "/api"
paths:
  /books/all:
    get:
      summary: "Get all books"
      description: "Get all books"
      operationId: "getAllBooks"
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
